#!/bin/bash

base=~/homes/Shong_DAN_bulk
fastq=${base}/1_fastq_renamed

## Merge (concatenate) FastQ files belonging to the same sample ID
mkdir -p ${base}/1_fastq_renamed_concatenated
cd ${fastq}
ls *R1* | cut -d _ -f 1,2 | sort | uniq | while read id; do \
cat $id*R1*.fastq.gz > ${base}/1_fastq_renamed_concatenated/$id.fastq.gz;
done
